"""initial schema

Revision ID: f974a8d18adb
Revises: 
Create Date: 2026-02-11 22:05:45.771946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f974a8d18adb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('entity_type', sa.Enum('champion', 'item', name='entitytype'), nullable=False),
    sa.Column('primary_role', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entities_name'), 'entities', ['name'], unique=True)
    op.create_table('patches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('release_date', sa.Date(), nullable=False),
    sa.Column('raw_notes', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patches_version'), 'patches', ['version'], unique=True)
    op.create_table('changes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patch_id', sa.UUID(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.Enum('damage', 'cooldown', 'base_stat', 'scaling', 'cost', 'mechanic', name='changecategory'), nullable=False),
    sa.Column('stat_name', sa.String(), nullable=False),
    sa.Column('ability_slot', sa.String(), nullable=True),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('delta_value', sa.Float(), nullable=True),
    sa.Column('delta_percent', sa.Float(), nullable=True),
    sa.Column('direction', sa.Enum('buff', 'nerf', 'adjustment', name='changedirection'), nullable=False),
    sa.Column('impact_weight', sa.Float(), nullable=False),
    sa.Column('impact_score', sa.Float(), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['patch_id'], ['patches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patch_entity_impacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patch_id', sa.UUID(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('total_impact_score', sa.Float(), nullable=False),
    sa.Column('buff_count', sa.Integer(), nullable=False),
    sa.Column('nerf_count', sa.Integer(), nullable=False),
    sa.Column('adjustment_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['patch_id'], ['patches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('patch_entity_impacts')
    op.drop_table('changes')
    op.drop_index(op.f('ix_patches_version'), table_name='patches')
    op.drop_table('patches')
    op.drop_index(op.f('ix_entities_name'), table_name='entities')
    op.drop_table('entities')
    # ### end Alembic commands ###
